name: Build JAR file
on: [push]
jobs:
  build-jar-file:
    runs-on: ubuntu-latest
    steps:
      - name: Get-Source
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.0.8'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew -PprojVersion=${{ github.run_number }} build
      - name: Run Tests with Gradle
        run: ./gradlew test --tests FantasyTeamControllerTest

      - name: Check imported libraries are secure and compliant
        id: datadog-software-composition-analysis
        uses: DataDog/datadog-sca-github-action@main
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_app_key: ${{ secrets.DD_APP_KEY }}
          dd_env: ci
          dd_service: curryware-java
          dd_site: datadoghq.com

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}

      - name: Build and Push Docker Container
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            BUILD_VERSION=${{ github.run_number }}
          platforms: linux/amd64, linux/arm64/v8
          push: true
          tags: scotcurry4/curryware-java:${{ github.run_number }}
          labels: |
            org.opencontainers.image.source=github.com/scotcurry/curryware-java
            org.opencontainers.image.revision=${{ github.sha }}
            tags.datadoghq.com/env=prod
            tags.datadoghq.com/version=${{ github.run_number }}
            tags.datadoghq.com/service=curryware-java
